### PR TITLE
Setup gradle for sandbox root

### PR DESCRIPTION
**Pull request by anshumg**

### CODE REVIEW

**Comment by madrob** [comment]
It's fine to check in the jar for now, but we should instead copy the modified gradlew scripts that we have on lucene-solr. There's a few extra workarounds in there - LUCENE-9471, LUCENE-9266

**Comment by anshumg** [comment]
@madrob - let me just copy them over right now in that case?

**Comment by madrob** [comment]
On second thought, since we don't know what/how we're going to be releasing from here, let's not worry about it until we need to.

**Review by madrob — APPROVED** [review]

**Comment by anshumg** [comment]
I've also updated the Gradle wrappers to bring in the fixes from lucene-solr.

**Comment by anshumg** [comment]
Thank you @madrob

**Pull request merged**
